volumes:
    leadtrack_postgres_data:
        name: leadtrack_postgres_data
        driver: local
    leadtrack_minio_data:
        name: leadtrack_minio_data
        driver: local
    leadtrack_mailpit_data:
        name: leadtrack_mailpit_data
        driver: local
    leadtrack_redis_data:
        name: leadtrack_redis_data
        driver: local
    leadtrack_nginx_logs:
        name: leadtrack_nginx_logs
        driver: local

services:
    server-service: &server-service
        build:
            context: .
            dockerfile: ./compose/server/dockerfile
        container_name: server-service
        depends_on:
            - postgres-service
            - minio-service
            - mailpit-service
            - redis-service
        volumes:
            - .:/app:z
        env_file:
            - ./.envs/.django.env
            - ./.envs/.postgres.env
        command: /start
        networks:
            - leadtrack_network

    celery-worker-service:
        <<: *server-service
        container_name: celery-worker-service
        image: celery-worker-service
        depends_on:
            - postgres-service
            - mailpit-service
            - minio-service
            - redis-service
        ports: []
        command: /start-celeryworker
        networks:
            - leadtrack_network

    celery-flower-service:
        <<: *server-service
        container_name: celery-flower-service
        image: celery-flower-service
        depends_on:
            - postgres-service
            - mailpit-service
            - minio-service
            - redis-service
        ports:
            - "5555:5555"
        command: /start-flower
        networks:
            - leadtrack_network

    postgres-service:
        image: postgres:16
        container_name: postgres-service
        volumes:
            - leadtrack_postgres_data:/var/lib/postgresql/data
        ports:
            - "5432:5432"
        env_file:
            - ./.envs/.postgres.env
        networks:
            - leadtrack_network

    minio-service:
        image: minio/minio:latest
        container_name: minio-service
        volumes:
            - leadtrack_minio_data:/data
        ports:
            - "9090:9090"
        env_file:
            - ./.envs/.minio.env
        command: server --console-address :9090 --address :9000 /data
        networks:
            - leadtrack_network

    mailpit-service:
        image: axllent/mailpit:latest
        container_name: mailpit-service
        volumes:
            - leadtrack_mailpit_data:/data
        ports:
            - "8025:8025"
        env_file:
            - ./.envs/.mailpit.env
        networks:
            - leadtrack_network

    redis-service:
        image: redis:6-alpine
        container_name: redis-service
        volumes:
            - leadtrack_redis_data:/data
        networks:
            - leadtrack_network

    nginx-service:
        build:
            context: .
            dockerfile: ./compose/nginx/dockerfile
        container_name: nginx-service
        depends_on:
            - server-service
        ports:
            - "8080:80"
        volumes:
            - leadtrack_nginx_logs:/var/log/nginx
        networks:
            - leadtrack_network

networks:
    leadtrack_network:
        driver: bridge
