volumes:
    leadtrack_postgres_data:
        name: leadtrack_postgres_data
        driver: local
    leadtrack_minio_data:
        name: leadtrack_minio_data
        driver: local
    leadtrack_nginx_logs:
        name: leadtrack_nginx_logs
        driver: local

services:
    server-service: &server-service
        build:
            context: .
            dockerfile: ./compose/server/dockerfile
        container_name: server-service
        depends_on:
            - postgres-service
            - minio-service
        volumes:
            - .:/app:z
        env_file:
            - ./.envs/.django.env
            - ./.envs/.postgres.env
        command: /start
        networks:
            - leadtrack_network

    postgres-service:
        image: postgres:16
        container_name: postgres-service
        volumes:
            - leadtrack_postgres_data:/var/lib/postgresql/data
        ports:
            - "5432:5432"
        env_file:
            - ./.envs/.postgres.env
        networks:
            - leadtrack_network

    minio-service:
        image: minio/minio:latest
        container_name: minio-service
        volumes:
            - leadtrack_minio_data:/data
        ports:
            - "9090:9090"
        env_file:
            - ./.envs/.minio.env
        command: server --console-address :9090 --address :9000 /data
        networks:
            - leadtrack_network

    nginx-service:
        build:
            context: .
            dockerfile: ./compose/nginx/dockerfile
        container_name: nginx-service
        depends_on:
            - server-service
        ports:
            - "8080:80"
        volumes:
            - leadtrack_nginx_logs:/var/log/nginx
        networks:
            - leadtrack_network

networks:
    leadtrack_network:
        driver: bridge
